### ISSUE TITLE
Spare slime b odies dont work with ling's revive abbility

### ISSUE THREAD

**Issue by Ludox235** [yogstation13/Yogstation-TG#2677]
[Round ID]: # 18713

[Reproduction]: # Be changeling, transform yourself into a slimeperson with xenobiology, make spare bodies, you cannot control bodies that are dead, therefore you cannot revive them with your ling abbility, if all of your body dies and the last one you controlled is cremated/gibbed you CANNOT go back inside one of your spare bodies to revive yourself, ruined changeling round :'(

**Comment by ThatLing** [comment]
Probably intended

**Comment by Ktlwjec** [comment]
I am like 99% sure that not being to move into other bodies whilst unconcious/dead is intended.

**Comment by Ludox235** [comment]
I know you arnet supposed to move into other bodies, but not being able to do this as a ling? it just negates the revive abbility

**Comment by MimicFaux** [comment]
If a ling is going to go through the trouble of making themself a slime person for backup bodies, just make yourself a backup auto-cloner.
